language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - pip install -U requests

script: python setup.py test

after_success:
  - pip install -r requirements-testing.txt -e .
  - py.test --cov=poultry --cov-report=term-missing tests
  - coveralls
