language: python

install:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

script: python setup.py test

after_success:
  - pip install -r requirements-testing.txt -e .
  - py.test --cov=poultry --cov-report=term-missing tests
  - coveralls
