language: python

install:
  - pip install python-coveralls

script: python setup.py test

after_success:
  - pip install -r requirements-testing.txt -e .
  - py.test --cov=google_ngram_downloader --cov-report=term-missing test
  - coveralls
