language: python
python:
  - "3.6"
install:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - pip install -U requests tox pytest
  - pip install -r requirements-testing.txt -e .

script: tox

after_success:
  - py.test --cov=poultry --cov-report=term-missing tests
  - coveralls
